name: mediascribe
channels:
  - pytorch          # PyTorch 官方源，优先
  - conda-forge      # 其次是 conda-forge，作为主要的包来源
  - defaults
dependencies:
  # Conda packages
  - python=3.10
  - ffmpeg           # The one and only command-line tool
  - pytorch          # Let conda handle the main library
  - yt-dlp
  - openai
  - pillow
  - transformers
  - numpy
  - scikit-learn
  - pymupdf
  - requests
  - pip
  
